name = "protomine"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
datamine = { path = "../datamine" }
argv = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
glam = ">= 2.0.2 and < 3.0.0"
justin = ">= 1.0.1 and < 2.0.0"
nbeet = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
